// <auto-generated />
namespace RSMuseum.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RegistrationAddProcessed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegistrationAddProcessed));
        
        string IMigrationMetadata.Id
        {
            get { return "201704210815342_Registration-AddProcessed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
